version: '3.8'

services:
  canctool:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      # 挂载主配置文件（必需）
      - ./providers_config.json:/app/providers_config.json:ro          # 使用自定义配置
      # 可选：挂载日志目录
      # - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加 nginx 反向代理
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - canctool
  #   restart: unless-stopped

networks:
  default:
    name: canctool-network
